source 'https://rubygems.org'

# Jekyll
gem "jekyll"
gem "jekyll-coffeescript"
gem "jekyll-sass-converter"

# Converters
gem "kramdown"
gem "maruku"
gem "rdiscount"
gem "redcarpet"
gem "RedCloth"

# Liquid
gem "liquid"

# Highlighters
gem "pygments.rb"

# Plugins
gem "jekyll-redirect-from"
gem "jekyll-sitemap"
