#!/bin/bash

# Defensive bash
set -ue

# Make sure the shell is bash:
[[ ${0} == *"bash"* ]] || { echo "Ops! Pipe me to bash"; exit 1; }

# Make sure you have curl and jq:
readonly CMD_CURL=$(type -P curl); [ -z "${CMD_CURL}" ] && { echo "Opss! curl is needed"; exit 1; }
readonly CMD_JQ=$(type -P jq); [ -z "${CMD_JQ}" ] && { echo "Ops! jq is needed"; exit 1; }

# Define the github repository API URL:
readonly KATO_URL='https://api.github.com/repos/katosys/kato'

# Discover the latest katoctl release for your OS/Arch:
KATOCTL=$(${CMD_CURL} -s ${KATO_URL}/releases | ${CMD_JQ} --raw-output \
  --arg SUFFIX $(uname | tr '[:upper:]' '[:lower:]')-$(uname -m) \
  '.[] | .assets[] | .browser_download_url | select(endswith($SUFFIX))' \
  | head -1)

# Download katoctl to /usr/local/bin:
echo "Downloadin katoctl to /usr/local/bin ..."
sudo ${CMD_CURL} -Lso /usr/local/bin/katoctl ${KATOCTL}
sudo chmod +x /usr/local/bin/katoctl
